---
version: "3"

services:
  microservice-solana-application-server:
    build:
      context: ../cmd/microservice-solana-application-server
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-solana-worker-retriever
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_SABER_SWAP_PROGRAM_ID: ${FLU_SOLANA_SABER_SWAP_PROGRAM_ID}
      FLU_SOLANA_SABER_RPC_URL: ${FLU_SOLANA_SABER_RPC_URL}
    depends_on:
      - redis
    restart: unless-stopped
