---
version: "3"

services:
  microservice-ethereum-application-server-usdt:
    build:
      context: ../cmd/microservice-solana-application-server
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-ethereum-application-server-usdt
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_ETHEREUM_APPLICATION_CONTRACT_ADDR: ${FLU_ETHEREUM_CONTRACT_ADDR_FUSDT}
      FLU_ETHEREUM_HTTP_URL: ${FLU_ETHEREUM_HTTP_URL}
      FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: ${FLU_ETHEREUM_TOKEN_DECIMALS_USDT}
    depends_on:
      - redis
    restart: unless-stopped

  microservice-ethereum-application-server-usdc:
    build:
      context: ../cmd/microservice-solana-application-server
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-ethereum-application-server-usdc
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_ETHEREUM_APPLICATION_CONTRACT_ADDR: ${FLU_ETHEREUM_CONTRACT_ADDR_FUSDC}
      FLU_ETHEREUM_HTTP_URL: ${FLU_ETHEREUM_HTTP_URL}
      FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: ${FLU_ETHEREUM_TOKEN_DECIMALS_USDC}
    depends_on:
      - redis
    restart: unless-stopped

  microservice-ethereum-application-server-dai:
    build:
      context: ../cmd/microservice-solana-application-server
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-ethereum-application-server-dai
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_ETHEREUM_APPLICATION_CONTRACT_ADDR: ${FLU_ETHEREUM_CONTRACT_ADDR_FDAI}
      FLU_ETHEREUM_HTTP_URL: ${FLU_ETHEREUM_HTTP_URL}
      FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: ${FLU_ETHEREUM_TOKEN_DECIMALS_DAI}
    depends_on:
      - redis
    restart: unless-stopped
