---
version: "3"

services:
  connector-common-twitter-hashtag-amqp:
    build:
      context: ../cmd/connector-common-twitter-hashtag-amqp
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-connector-common-twitter-hashtag-amqp
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_TWITTER_BEARER_TOKEN: ${FLU_TWITTER_BEARER_TOKEN}
      FLU_TWITTER_HASHTAGS: ${FLU_TWITTER_HASHTAGS}
    restart: unless-stopped
