---
version: "3"

services:
  microservice-ethereum-worker-server-usdt:
    build:
      context: ../cmd/microservice-ethereum-worker-server
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-ethereum-worker-server-usdt
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_ETHEREUM_CONTRACT_ADDR: ${FLU_ETHEREUM_CONTRACT_ADDR_FUSDT}
      FLU_ETHEREUM_HTTP_URL: ${FLU_ETHEREUM_HTTP_URL}
      FLU_ETHEREUM_TOKEN_BACKEND: compound
      FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR: ${FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR}
      FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: ${FLU_ETHEREUM_TOKEN_NAME_USDT}
      FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: ${FLU_ETHEREUM_TOKEN_DECIMALS_USDT}
      FLU_ETHEREUM_CTOKEN_ADDR: ${FLU_ETHEREUM_CTOKEN_ADDR_USDT}
      FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdt
      FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.usdt.apy.moving-average
    restart: unless-stopped

  microservice-ethereum-worker-client-usdt:
    build:
      context: ../cmd/microservice-ethereum-worker-client
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-ethereum-worker-server-usdt
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_ETHEREUM_CONTRACT_ADDR: ${FLU_ETHEREUM_CONTRACT_ADDR_FUSDT}
      FLU_ETHEREUM_HTTP_URL: ${FLU_ETHEREUM_HTTP_URL}
      FLU_ETHEREUM_WORKER_PRIVATE_KEY: ${FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDT}
      FLU_ETHEREUM_GAS_LIMIT: ${FLU_ETHEREUM_WORKER_GAS_LIMIT_USDT}
      FLU_ETHEREUM_HARDHAT_FIX: ${FLU_ETHEREUM_WORKER_HARDHAT_FIX_USDT}
      FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdt
    restart: unless-stopped
