name: Mainnet (Auto)

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: mainnet

jobs:
 build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: mainnet
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - name: Get Diff
        id: diff
        uses: ./scripts/actions
        with:
          command: |
            flu get-diff --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Build
        id: build
        uses: ./scripts/actions
        with:
          command: |
            flu build-docker-diff --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Deploy
        id: deploy
        uses: ./scripts/actions
        with:
          command: |
            flu deploy-service-diff --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Discord notif (SUCCESS)
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          description: "**Title:** [${{ github.event.pull_request.title }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n**Author:** ${{ github.event.pull_request.user.login }}\n**Event:** ${{ github.event_name }}\n**Repository:** ${{ github.event.repositoy.full_name }}\n**Environment:** ${{ env.ENVIRONMENT }}\n**Approved by:** ${{ github.event.sender.login }}\n\n"
          details: Deployment succeeded.
          webhookUrl: ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }}
      - name: Discord notif (CANCEL)
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          description: "**Title:** [${{ github.event.pull_request.title }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n**Author:** ${{ github.event.pull_request.user.login }}\n**Event:** ${{ github.event_name }}\n**Repository:** ${{ github.event.repositoy.full_name }}\n**Environment:** ${{ env.ENVIRONMENT }}\n**Approved by:** ${{ github.event.sender.login }}\n\n"
          details: Deployment cancelled.
          webhookUrl: ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }}
      - name: Discord notif (FAIL)
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          description: "**Title:** [${{ github.event.pull_request.title }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n**Author:** ${{ github.event.pull_request.user.login }}\n**Event:** ${{ github.event_name }}\n**Repository:** ${{ github.event.repositoy.full_name }}\n**Environment:** ${{ env.ENVIRONMENT }}\n**Approved by:** ${{ github.event.sender.login }}\n\n"
          details: Deployment failed.
          webhookUrl: ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }}
